project_id = "faceitdltest"
region     = "europe-west2"
location_id   = "europe-west2"
project = "faceitdltest"
name             = "dltest12345"
database_version = "POSTGRES_14"
zone = "europe-west2"
