project_id = "dl-test-354519"
region     = "europe-west2"
location_id   = "europe-west2"
project = "dl-test-354519"
name             = "faceit-test"
database_version = "POSTGRES_14"
zone = "europe-west2"