apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  selector:
    matchLabels:
      run: test-app
  replicas: 1
  template:
    metadata:
      labels:
        run: test-app
    spec:
      containers:
        - name: test-app
          image: eu.gcr.io/dl-project-354114/test-app@sha256:1ad21e8573219da7c20f98e23c3669df135c84f3de634915f1f728c225b4e2fd
          env:
          - name: POSTGRESQL_DBNAME
            value: "postgrestest"
          - name: POSTGRESQL_HOST
            value: "10.193.112.3"
          - name: POSTGRESQL_PASSWORD
            value: "mysecretpassword"
          - name: POSTGRESQL_PORT
            value: "5432"
          - name: POSTGRESQL_USER
            value: "postgres"
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m