apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: eu.gcr.io/dl-project-354114/test-app:latest
        ports:
        - containerPort: 80